# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Build Ant Sample 123 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p ${{ github.workspace }}/mydir
    - run: echo hello > ${{ github.workspace }}/mydir/world.txt
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    -  name: Upload
       uses: actions/upload-artifact@v3
       with:
        name: my-artifact
        path: ${{ github.workspace }}/mydir/world.txt
